fix: obj.Call调用dbus接口异常，改用go-dbus-factory
使用go-dbus-factory替换obj.Call，异常如下
daemon/system/keyevent[10523]: manager.go:153: com.deepin.system.InputDevices.TouchPad.SetTouchPadEnable err :  Object does not implement the interface
go-dbus-factory: https://gerrit.uniontech.com/c/go-dbus-factory/+/196548

Log:
Influence: 接口调用
Bug: https://pms.uniontech.com/bug-view-198847.html
Change-Id: Ied0a6d0ebc3fe0eabfc89984a0d78bdf6dfc16cc
(cherry picked from commit 815ab63666f6a60c251a9b0b8e03faf8350661c3)